name: Build and Push to ACR

on:
    # push:
  #   paths:
  #     - 'application/**'  # Trigger on changes in the application directory
  workflow_run:
    workflows: ["Terraform infrastructure push"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR 
      run: |
        az acr login --name infraacr1952
    
    - name: Docker build and push Docker image to ACR
      run: |
        docker build -t infraacr1952.azurecr.io/react-portfolio-app:v1 ./application
        docker push infraacr1952.azurecr.io/react-portfolio-app:v1

    - name: Set AKS CLI
      run: |
        az aks get-credentials --resource-group infra-rg-dev-5690 --name infra-aks-dev-5690

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        kubectl apply -f k8s/ingress.yml
        kubectl get all
    
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services
