name: Build and Push to ACR

on:
    push:
     paths:
      - 'application/**'  # Trigger on changes in the application directory
    # workflow_run:
    #  workflows: ["Terraform infrastructure push"]
    #  types:
    #   - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR 
      run: |
        az acr login --name infraacrdev
    
    - name: Docker build and push Docker image to ACR
      run: |
        docker build -t infraacrdev.azurecr.io/react-portfolio-app:v1 ./application
        docker push infraacrdev.azurecr.io/react-portfolio-app:v1

    - name: Set AKS CLI 
      run: |
        az aks get-credentials --resource-group infra-rg --name infraaks

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        kubectl apply -f k8s/ingress.yml
        kubectl get all
    
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get services

    - name: Send notification to MS Teams
      uses: toko-bifrost/ms-teams-deploy-card@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
        card-layout-exit: complete
        show-on-exit: true
