name: Terraform infrastructure provision 

on:
  push:
    paths:
      - 'terraform/**'  # Trigger on changes in the terraform directory
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action (apply or plan)'
        required: true
        default: 'apply'
      
jobs:
    terraform:
      runs-on: ubuntu-latest
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      defaults:
        run:
         working-directory: ./terraform
          
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.5.7
          
        - name: Terraform Init
          run: terraform init 

        - name: Terraform format
          run: terraform fmt -recursive ##for subsdirectories

        - name: Terraform Plan
          if: ${{ github.event_name == 'push' || github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' }}
          run: terraform plan
          env:
            TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

        - name: Terraform Apply
          if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply') }}
          run: terraform apply --auto-approve


        - name: Send notification to MS Teams
          if: always()
          uses: toko-bifrost/ms-teams-deploy-card@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
            card-layout-exit: complete
            show-on-exit: true

