name: Terraform infrastructure push

on:
  # push:
  #   paths:
  #     - 'terraform/**'  # Trigger on changes in the terraform directory
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action (apply or plan)'
        required: true
        default: 'apply'
      
jobs:
    terraform:
      runs-on: ubuntu-latest
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      defaults:
        run:
         working-directory: ./terraform
          
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.5.7
          
        - name: Terraform Init
          run: terraform init 

        - name: Terraform format
          run: terraform fmt -recursive ##for subsdirectories

        - name: Terraform Plan
          run: terraform plan
          env:
            TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

        - name: Terraform Apply
          run: terraform apply --auto-approve     
          
        - name: Capture Terraform Output
          id: tf_output
          run: |
            echo "RG_NAME=$(terraform output -raw resource_group_name)" >> $GITHUB_ENV
            echo "AKS_CLUSTER_NAME=$(terraform output -raw aks_cluster_name)" >> $GITHUB_ENV
            echo "ACR_NAME=$(terraform output -raw acr_name)" >> $GITHUB_ENV

        - name: Write Terraform outputs to file
          run: |
            echo "resource_group_name=${{ env.RG_NAME }}" >> terraform_outputs.txt
            echo "aks_cluster_name=${{ env.AKS_CLUSTER_NAME }}" >> terraform_outputs.txt
            echo "acr_name=${{ env.ACR_NAME }}" >> terraform_outputs.txt

        - name: Upload Terraform workflow artifacts
          uses: actions/upload-artifact@v3
          with:
            name: terraform-outputs
            path: terraform_outputs.txt

        - name: Send notification to MS Teams
          if: always()
          uses: toko-bifrost/ms-teams-deploy-card@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
            card-layout-exit: complete
            show-on-exit: true

